export { default as Head } from "./Head.astro";
export { default as I18n } from "./I18n.astro";
export { default as Header } from "./header/Header.astro";
export { default as Contact } from "./contact/Contact.astro";
export { default as Footer } from "./Footer.astro";
export { default as HeadingCentered } from "./HeadingCentered.astro";
export { default as HeadingLeftAligned } from "./HeadingLeftAligned.astro";
export { default as LanguageSelector } from "./LanguageSelector.astro";
export { default as Prose } from "./Prose.astro";
